wallpaper {
monitor = DP-2
path = ~/Pictures/akira-toriyama-dragon-ball-scaled.jpg
fit_mode = fill
}

wallpaper {
monitor = HDMI-A-2
path = ~/Pictures/akira-toriyama-dragon-ball-scaled.jpg 
fit_mode = fill
}

splash = false
ipc = off
